Import( 'env' )
Import( 'loudnessAssessmentVersionStr' )
Import( 'loudnessAnalyserLibStatic' )

### loudness Tools ###

loudnessToolsLibName = 'loudnessTools'
# add version number to the name of the shared library if Windows platform
if env['PLATFORM'] == 'win32':
    loudnessToolsLibName += '-' + loudnessAssessmentVersionStr

loudnessToolsSrc = Glob( '*.cpp' )

loudnessToolsDeps = [
    loudnessAnalyserLibStatic,
]

loudnessToolsLib = env.SharedLibrary(
    target = loudnessToolsLibName,
    source = loudnessToolsSrc,
    LIBS = loudnessToolsDeps,
)

loudnessToolsLibStatic = env.StaticLibrary(
    target = 'loudnessTools',
    source = loudnessToolsSrc,
    LIBS = loudnessToolsDeps,
)

# Install
env.Alias( 'install', env.InstallVersionedLib( 'lib', loudnessToolsLib ) )
env.Alias( 'install', env.Install( 'lib', loudnessToolsLibStatic ) )

Export( 'loudnessToolsLibStatic' )
